### ISSUE TITLE
Add the "return to top" button on mobile facility pages

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#417] opened 2019-10-02 13:51 UTC
## Current state 
The return to top button is missing from the facility pages. 

## Desired state 
The return to top button is on all pages.

**Comment by allisonnorman** [comment] 2019-10-02 15:58
Back to top has been implemented on all mobile pages. We have an issue open for desktop but moved it to out of scope for MVP (#394) Do you think adding this to desktop is important for MVP launch?

**Comment by bpdesigns** [comment] 2019-10-02 17:01
@allisonnorman can you confirm that the link is there on the Facility pages? I just double checked and I don't see the link on those pages. 

I don't think the desktop link is important for MVP

**Comment by allisonnorman** [comment] 2019-10-02 21:23
Good catch. I think it was intended to be on all page. I'll pull this in.

**Closed** 2019-10-03 16:50 UTC
Labels: enhancement, high-priority
